### PR TITLE
Update Kyuubi HA Guide to latest configuration parameters

### PR DESCRIPTION
**Pull request by yangrong688**
yangrong688 [Closes #355](https://github.com/yaooqinn/kyuubi/pull/355)    Target Issue Test Plan Doc [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

Update HA doc to latest configuration parameters.

### CODE REVIEW

**Comment by yaooqinn** [comment]
this looks great! thanks for the help in improving the documentation!

Please update the HA guide w.s.t https://kyuubi.readthedocs.io/en/latest/deployment/settings.html#ha

**Comment by yangrong688** [comment]
It seems HA guide's configuration in https://kyuubi.readthedocs.io/en/latest/deployment/settings.html#ha is already the latest version.
I found that the prefix of configuration parameter in docs/deployment/high_availability_guide.md and docs/deployment/settings.md are different.
 In settings.md all configuration parameters start with kyuubi, while it start with spark.kyuubi in high_availability_guide.md.
Shall I change configuration parameter prefix to kyuubi in high_availability_guide.md?

**Comment by ulysses-you** [comment]
@yangrong688 thanks for the investigation. Seems the docs of `high_availability_guide` is outdate.

The right way to set ha config is add these to `kyuubi-defaults.conf` with the prefix `kyuubi.` instead of add `spark.kyuubi.` to `spark-defaults.conf`. So I believe you can update the related things.

**Comment by yaooqinn** [comment]
yes,  the `settings.md` consists of all new configurations which will keep updating automatically according to the source code.  When we need to describe a feature in detail where we may refer to some of the configs, we respect `settings.md`.

```high_availability_guide.md``` is out of date. Also any doc does not start with a new `KYUUBI LOGO` may be outdate

**Comment by yaooqinn** [comment]
> Shall I change configuration parameter prefix to kyuubi in high_availability_guide.md?
You can just copy the table of `Ha` from settings.md to the section [here](https://kyuubi.readthedocs.io/en/latest/deployment/high_availability_guide.html#configuring-high-availability) and update the rest of the doc accordingly.

**Comment by yangrong688** [comment]
> > Shall I change configuration parameter prefix to kyuubi in high_availability_guide.md?
> 
> You can just copy the table of `Ha` from settings.md to the section [here](https://kyuubi.readthedocs.io/en/latest/deployment/high_availability_guide.html#configuring-high-availability) and update the rest of the doc accordingly.

OK, I will deal with it .

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master for v1.2.0

**Pull request closed without merging**
