### PR TITLE
[KYUUBI #304]  Add kyuubi-ctl shell script

### PR DESCRIPTION
**Pull request by turboFei**
turboFei [Closes #512](https://github.com/yaooqinn/kyuubi/pull/512)    [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _Why are the changes needed?_

Add shell script `kyuubi-ctl` to launch kyuubi service control client.

### _How was this patch tested?_
Run test locally.
image

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
list:
image

**Comment by turboFei** [comment]
get

**Comment by turboFei** [comment]
create:
image

**Comment by pan3793** [comment]
The script LGTM. One question, I saw you run `sh bin/kyuubi-ctl` in screenshot, have you set `x` permission on `bin/kyuubi-ctl`? The git will track the unix permissions of file.

I have a look on `build/dist`, we don't run `chmod +x bin/*` when make dist, and suppose the `dist` only running on UNIX-like OS, so the permission is retained.

**Comment by turboFei** [comment]
delete:
image

**Comment by turboFei** [comment]
Its permission is same with `bin/kyuubi`
```
-rwxr-xr-x  1 fwang12  110525255   1.6K Apr 12 14:15 bin/kyuubi-ctl
```

**Review by pan3793 — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
Other question,
For the embedded zookeeper use case,
I have to set below two parameters.

```
kyuubi.zookeeper.embedded.data.dir /kyuubi
kyuubi.ha.zookeeper.namespace /kyuubi
```

**Comment by yaooqinn** [comment]
> Will follow it and try to combine these two parameters.

I don't get it, what do you mean about `combine`?

**Comment by yaooqinn** [comment]
Can you omit `sh` and test locally too?

**Comment by turboFei** [comment]
> > Will follow it and try to combine these two parameters.
> 
> I don't get it, what do you mean about `combine`?


At first, I started kyuubi server with `kyuubi.zookeeper.embedded.data.dir=/kyuubi` and did not define the value of kyuubi.ha.zookeeper.namespace.


For create action, the namespace transferred is toNamespace, and the fromNamepace is loaded by the key of `kyuubi.ha.zookeeper.namespace`, which was not defined in kyuubi-defaults.conf.
So, we need some fallback for the default namespace.

**Comment by yaooqinn** [comment]
image

This command usage hint looks confusing, we may improve it later. @pan3793 do you think we should use `common-cli` or something as simple as it to do the command parse?

**Comment by turboFei** [comment]
It works well without `sh`.
image

**Comment by yaooqinn** [comment]
> > > Will follow it and try to combine these two parameters.
> > 
> > 
> > I don't get it, what do you mean about `combine`?
> 
> At first, I started kyuubi server with `kyuubi.zookeeper.embedded.data.dir=/kyuubi` and did not define the value of kyuubi.ha.zookeeper.namespace.
> 
> For create action, the namespace transferred is toNamespace, and the fromNamepace is loaded by the key of `kyuubi.ha.zookeeper.namespace`, which was not defined in kyuubi-defaults.conf.
> So, we need some fallback for the default namespace.

image

image

**Comment by yaooqinn** [comment]
the get/list looks exactly the same.

For followups,
1. I think the `get` should return the znode.toString, as something like `serverUrl......version=...seq...`
2. the result wrapping seems to make the command pipeline a bit hard? `list foreach delete` for `delete-all`?
3. I am not sure these commands are working well when ACL or SSL enabled,
4. Shall we also setACL/getACL actions?

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
> image
> 
> This command usage hint looks confusing, we may improve it later. @pan3793 do you think we should use `common-cli` or something as simple as it to do the command parse?

+1 for leveraging library to build cli parser.

**Pull request closed without merging**
