### PR TITLE
[Kyuubi-1.0] Update built-in Spark version to 3.0.2

### PR DESCRIPTION
**Pull request by ulysses-you**
ulysses-you [Closes #357](https://github.com/yaooqinn/kyuubi/pull/357)    Target Issue Test Plan [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

backport [#356](https://github.com/yaooqinn/kyuubi/pull/356) for branch-1.0.

### _Why are the changes needed?_

Spark 3.0.2 has been released now.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @yaooqinn

**Comment by yaooqinn** [comment]
Does it conflict when directly backports?

**Comment by ulysses-you** [comment]
Just forgot to backport at that time..

**Comment by yaooqinn** [comment]
we can re-run the `merge` script target the same PR number.

**Comment by yaooqinn** [comment]
thanks, merged to branch 1.0

**Pull request closed without merging**
