### PR TITLE
[KYUUBI #306] SparkProcessBuilder support Windows

### PR DESCRIPTION
**Pull request by Honglun**
Honglun [Closes #335](https://github.com/yaooqinn/kyuubi/pull/335)    [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _Why are the changes needed?_

SparkProcessBuilder support Windows. Easy to test for developers using Windows.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request
image

### CODE REVIEW

**Comment by Honglun** [comment]
@yaooqinn Updating the user name requires updating all the file information, which is very troublesome, so I created a new PR.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master for v1.1.0

**Comment by yaooqinn** [comment]
can we also make a PR to support server instance in win？

**Comment by Honglun** [comment]
For Windows, it's mostly for testing, I think it's good enough to run with an IDE.

**Pull request closed without merging**
