### PR TITLE
Add Fei Wang to collaborators

### PR DESCRIPTION
**Pull request by turboFei**
turboFei [Closes #486](https://github.com/yaooqinn/kyuubi/pull/486)    Target Issue Test Plan Doc [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _Why are the changes needed?_
Update collaborators list.

### CODE REVIEW

**Comment by yaooqinn** [comment]
Congrats!

**Comment by turboFei** [comment]
Thanks

**Comment by yaooqinn** [comment]
https://github.com/yaooqinn/kyuubi/blob/master/dev/merge_kyuubi_pr.py Please refer to this tool to take your first shot

**Comment by turboFei** [comment]
Got it.

**Comment by ulysses-you** [comment]
ah welcome ~

**Pull request closed without merging**
