### PR TITLE
Detected Dependency List Change for better dependency management

### PR DESCRIPTION
**Pull request by yaooqinn**
yaooqinn [Closes #416](https://github.com/yaooqinn/kyuubi/pull/416)    Target Issue [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _Why are the changes needed?_

Detect Dependency List Change, to let us and users know what actually release with Kyuubi
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @pan3793 @ulysses-you please take a look

**Comment by pan3793** [comment]
It's pretty good! And I think we also need to update document to tell contributors what they should do when change dependencies?

**Comment by yaooqinn** [comment]
good point~ Let me update the doc

**Review by pan3793 — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master for v1.2.0

**Pull request closed without merging**
