### PR TITLE
Support user specify app name and tag

### PR DESCRIPTION
**Pull request by ulysses-you**
ulysses-you [Closes #365](https://github.com/yaooqinn/kyuubi/pull/365)    Target Issue [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

After this PR, we will submit spark app with such command.
```
./dist/externals/spark-3.0.1-bin-hadoop2.7/bin/beeline -u "jdbc:hive2://10.242.146.27:10009/;#spark.app.name=test" 
```
```
2021-02-24 14:40:53.606 INFO session.KyuubiSessionImpl: Launching SQL engine: /Users/cathy/Desktop/code/kyuubi/dist/externals/spark-3.0.1-bin-hadoop2.7/bin/spark-submit \
	--class org.apache.kyuubi.engine.spark.SparkSQLEngine \
	--conf spark.app.name=test \
	--conf spark.hive.server2.thrift.resultset.default.fetch.size=1000 \
	--conf spark.kyuubi.ha.zookeeper.namespace=/kyuubi_USER/anonymous \
	--conf spark.kyuubi.ha.zookeeper.quorum=127.0.0.1:2181 \
	--conf spark.yarn.tags=KYUUBI \
	--conf spark.kyuubi.ha.zookeeper.acl.enabled=false \
```

### CODE REVIEW

**Comment by ulysses-you** [comment]
@yaooqinn

**Comment by yaooqinn** [comment]
also, cc @pan3793 as a new collaborator

**Comment by yaooqinn** [comment]
`spark.yarn.tags` is a seq, we should do append

**Comment by yaooqinn** [comment]
I suggest we add `spark.yarn.applicationType` with `KYUUBI / SPARK`

**Comment by pan3793** [comment]
>
```
beeline -u "jdbc:hive2://10.242.146.27:10009/;#spark.app.name=test" 
```

`#` is needed? `beeline --help` shows:
```
4. Connect using SSL connection to HiveServer2 on localhost at 10000
$ beeline jdbc:hive2://localhost:10000/default;ssl=true;sslTrustStore=/usr/local/truststore;trustStorePassword=mytruststorepassword
```

**Comment by yaooqinn** [comment]
> > 
> 
> ```
> beeline -u "jdbc:hive2://10.242.146.27:10009/;#spark.app.name=test" 
> ```
> 
> `#` is needed? `beeline --help` shows:
> 
> ```
> 4. Connect using SSL connection to HiveServer2 on localhost at 10000
> $ beeline jdbc:hive2://localhost:10000/default;ssl=true;sslTrustStore=/usr/local/truststore;trustStorePassword=mytruststorepassword
> ```

I am not 100% sure but this is a behavior of HiveJDBC. I guess `#` is a separator used there for distinguishing `hivevar` and `hiveconf` or something else.

**Comment by pan3793** [comment]
OK, I found it from Hive wiki.

```
Connection URL Format
The HiveServer2 URL is a string with the following syntax:

jdbc:hive2://<host1>:<port1>,<host2>:<port2>/dbName;initFile=<file>;sess_var_list?hive_conf_list#hive_var_list

where

<host1>:<port1>,<host2>:<port2> is a server instance or a comma separated list of server instances to connect to (if dynamic service discovery is enabled). If empty, the embedded server will be used.
dbName is the name of the initial database.
<file> is the path of init script file (Hive 2.2.0 and later). This script file is written with SQL statements which will be executed automatically after connection. This option can be empty. 
sess_var_list is a semicolon separated list of key=value pairs of session variables (e.g., user=foo;password=bar).
hive_conf_list is a semicolon separated list of key=value pairs of Hive configuration variables for this session
hive_var_list is a semicolon separated list of key=value pairs of Hive variables for this session.
Special characters in sess_var_list, hive_conf_list, hive_var_list parameter values should be encoded with URL encoding if needed.
``

**Comment by yaooqinn** [comment]
> OK, I found it from Hive wiki.

Can we inline this in our doc？

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged!

**Comment by ulysses-you** [comment]
thanks @pan3793 @yaooqinn

**Pull request closed without merging**
