### PR TITLE
GetSchemas supports DSv2 multipart namespaces

### PR DESCRIPTION
**Pull request by yaooqinn**
yaooqinn [Closes #334](https://github.com/yaooqinn/kyuubi/pull/334)    Target Issue [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=yaooqinn&utm_campaign=badge_info)

### _Why are the changes needed?_

This PR adds support for using Spark DSv2 to get Schemas with multipart namespaces under multiple catalogs.

The current works are all based on Apache Iceberg.

TODOS:
    next step we will support get tables operation for multiple catalogs and namespaces.

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

image

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan, It seems to work fine with Dbeaver and Apache Iceberg, the `hive-jdbc` module also feed `.` to the client-side as a valid character.

We can make this happen in the Spark thrift server too.

@rdblue @aokolnychyi It would be nice if we could get help from the Apache Iceberg community

**Comment by rdblue** [comment]
@yaooqinn, what would you like our help with?

**Comment by yaooqinn** [comment]
> @yaooqinn, what would you like our help with?

@rdblue thanks for your response, I'd like to know whether the `listNamespaces` or `listTables` will support SQL wildcards `%` and `_`?

**Comment by rdblue** [comment]
I'm not sure if there is a good justification for adding that to the interface. It would be simple enough to add, but there is the extra complexity in the interface to consider. I don't think that pushing the pattern into the interface adds much value because there aren't many cases where you actually need to push the pattern down to the underlying store. Databases probably have at most a few thousand tables, which is isn't a high cost to send as identifiers or a high cost to filter in Spark. So keeping the complexity in Spark seems like a good idea to me, rather than adding an extra method that implementations need to deal with.

**Comment by yaooqinn** [comment]
Thanks for the clarification.  I see your point. +1 for keeping the simplification for DSv2 APIs. My biggest concern is the stability of the APIs, as they are mainly designed for the underlying systems to implement and for Spark to call, not for other readers like what we do here. So the stability and simplicity are good to me.

And thanks again.

**Pull request closed without merging**
